---

- name: create consul group
  group:
    name: '{{ consul_group }}'
    state: present
    system: yes
  register: create_consul_group

- name: create consul user
  user:
    name: '{{ consul_user }}'
    group: '{{ consul_group }}'
    system: yes
    create_home: no
  when: create_consul_group.changed

- name: create consul directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: '{{ consul_group }}'
    mode: 0770
  with_items:
    - '{{ consul_config_dir }}'
    - '{{ consul_data_dir }}'

- name: place systemd unit
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0664
  register: place_systemd_unit

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
  when: place_systemd_unit.changed


- block:

    - name: read agent token
      shell: awk -F '"' '/agent/ { print $2 }' /etc/consul.d/consul.hcl | sed 's/"//g'
      failed_when: false
      changed_when: false
      register: read_agent_token

    - set_fact:
        consul_acl_agent_token: '{{ read_agent_token.stdout }}'

  when: consul_acl_enable | bool


- name: place config
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: root
    group: '{{ consul_group }}'
    mode: 0640
    validate: 'consul validate -config-format=hcl -quiet %s'
  register: place_config

- name: place consul sysconfig
  template:
    src: sysconfig.consul.j2
    dest: /etc/sysconfig/consul
    owner: root
    group: '{{ consul_group }}'
    mode: 0640
  register: place_consul_sysconfig


- block:

    - name: create cert directory
      file:
        path: /etc/consul.d/tls
        owner: root
        group: '{{ consul_group }}'
        mode: 0750
        state: directory

    - name: place certs
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: root
        group: '{{ item.group }}'
        mode: 0640
      with_items:
        - { src: "{{ consul_ca_file }}",    dest: /etc/consul.d/tls/ca.crt,           group: "{{ consul_group }}" }
        - { src: "{{ consul_ca_file }}",    dest: /etc/pki/ca-trust/source/anchors/,  group: root                 }
        - { src: "{{ consul_cert_file }}",  dest: /etc/consul.d/tls/consul.crt,       group: "{{ consul_group }}" }
        - { src: "{{ consul_key_file }}",   dest: /etc/consul.d/tls/consul.key,       group: "{{ consul_group }}" }
      register: place_certs

    - name: update ca trust
      shell: update-ca-trust
      when: place_certs.changed

  when:
    - consul_use_tls | bool
    - not skip_certs | d (False)


- name: consul restart
  systemd:
    name: consul
    state: restarted
    enabled: yes
  when: place_config.changed or place_consul_sysconfig.changed or place_certs.changed
  register: consul_restart
